words = input()
sc_list = list('[@!#$%^&*()<>?/\|}{~:]')
under = len(list(filter(lambda x: x == '_', words)))
low = len(list(filter(lambda x: x.islower(), words)))
upp = len(list(filter(lambda x: x.isupper(), words)))
sym = len(words) - (under + low + upp)
print(under/len(words))
print(low/len(words))
print(upp/len(words))
print(sym / len(words))